### ISSUE TITLE
Powering mechanism?

### ISSUE THREAD

**Issue by s390x** [jim11662418/wheelwriter-teletype#1]
Is power (VCC for the MCU, etc) being provided from the USB host or the wheelwriter typewriter?
Also, I have tried to summarize a parts list for this project and annotate your image, did you use two caps as per your schematic?
Sorry I am not an electrical engineer so this is new to me, I need a parts list for ordering.
![wheelwriter-interface-annotated](https://user-images.githubusercontent.com/87795759/126736220-5980b590-a5f1-47e6-ae7c-c1d8acdebc60.jpg)

**Comment by jim11662418** [comment]
Sorry that I didn't see this earlier. 
Power for the MCU is being provided by the Wheelwriter. The capacitor next to the MCU is 22 uF. The 0.1 uF capacitor is on the under side of the board connected to pins 18 and 20 of the MCU socket.

**Comment by s390x** [comment]
Thank you!
