### ISSUE TITLE
Can this be used to send commands to the typewriter?

### ISSUE THREAD

**Issue by RamiAwar** [jim11662418/wheelwriter-teletype#2]
Hello! I'm looking for projects that have already built controllers for type writers as I'm trying to use my normal keyboard to trigger typewriter prints.

Is this project suitable / modifiable in such a way so as to make that possible?

**Comment by jim11662418** [comment]
I have a project here <https://github.com/jim11662418/wheelwriter-printer> that
uses a PS/2 keyboard to send characters to a Wheelwriter.
